<?php

namespace RieunierZeferino\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompositionOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionOeuvreRepository extends EntityRepository
{
    public function getComposition($id)
    {
        $qr = $this->_em->createQueryBuilder()
            ->select('IDENTITY(compooeuvre.codeComposition)')
            ->from('CatalogueBundle:CompositionOeuvre', 'compooeuvre')
            ->join('compooeuvre.codeOeuvre', 'oeuvre')
            ->join('compooeuvre.codeComposition', 'compo')
            ->where('compooeuvre.codeOeuvre=:id')
            ->setMaxResults(1)
            ->setParameter('id', $id);
        return $qr->getQuery()->getSingleScalarResult();
    }
}
