<?php

namespace RieunierZeferino\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnregistrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnregistrementRepository extends EntityRepository
{
    public function getExtraitOeuvre($id)
    {
        $query = $this->_em->createQueryBuilder()
            ->select('enregistrement.extrait')
            ->from('RieunierZeferino\CatalogueBundle\Entity\Enregistrement', 'enregistrement')
            ->join('enregistrement.codeComposition', 'composition')
            ->where('composition.codeComposition=:id')
            ->setMaxResults(1)
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getSingleScalarResult();
    }
}
