Composition:
    type: entity
    table: Composition
    id:
        codeComposition:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Composition
            generator:
                strategy: IDENTITY
    fields:
        titreComposition:
            type: string
            nullable: false
            length: 0
            fixed: false
            column: Titre_Composition
        année:
            type: integer
            nullable: true
            unsigned: false
            column: Année
        composanteComposition:
            type: string
            nullable: true
            length: 0
            fixed: false
            column: Composante_Composition
    lifecycleCallbacks: {  }
