Enregistrement:
    type: entity
    table: Enregistrement
    indexes:
        IDX_CC3BD8F7D49D5E5D:
            columns:
                - Code_Composition
    id:
        codeMorceau:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Morceau
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 0
            fixed: false
            column: Titre
        nomDeFichier:
            type: string
            nullable: false
            length: 0
            fixed: false
            column: Nom_de_Fichier
        durée:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: Durée
        duréeSeconde:
            type: integer
            nullable: true
            unsigned: false
            column: Durée_Seconde
        prix:
            type: integer
            nullable: true
            unsigned: false
            column: Prix
        extrait:
            type: blob
            nullable: true
            length: null
            fixed: false
            column: Extrait
    manyToOne:
        codeComposition:
            targetEntity: Composition
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Composition:
                    referencedColumnName: Code_Composition
            orphanRemoval: false
    lifecycleCallbacks: {  }
