Interpréter:
    type: entity
    table: Interpréter
    indexes:
        IDX_12B376CFE694D5AB:
            columns:
                - Code_Musicien
        IDX_12B376CFD990D4F0:
            columns:
                - Code_Morceau
        IDX_12B376CFD389A975:
            columns:
                - Code_Instrument
    id:
        codeInterpréter:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Interpréter
            generator:
                strategy: IDENTITY
    manyToOne:
        codeMusicien:
            targetEntity: Musicien
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Musicien:
                    referencedColumnName: Code_Musicien
            orphanRemoval: false
        codeMorceau:
            targetEntity: Enregistrement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Morceau:
                    referencedColumnName: Code_Morceau
            orphanRemoval: false
        codeInstrument:
            targetEntity: Instrument
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Instrument:
                    referencedColumnName: Code_Instrument
            orphanRemoval: false
    lifecycleCallbacks: {  }
