parameters:
#    catalogue.example.class: RieunierZeferino\CatalogueBundle\Example

services:
#    catalogue.example:
#        class: %catalogue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
